### ISSUE TITLE
(พืช)ขายสินค้าในราคาปกติ แต่แจ้งเตือนขออนุมัติ

### ISSUE THREAD

**Issue by satawat-t** [tarro55/kkc#16]
User ทำการขายสินค้าตัวนี้ ราคา 1100 บาท แต่ระบบแจ้งว่าขายต่ำกว่าราคาขั้นต่ำครับ ราคาขั้นต่ำสินค้าตัวนี้คือ 790 บาท
![image](https://user-images.githubusercontent.com/60998712/86199126-7cf8a000-bb83-11ea-960e-137c8c22395a.png)

**Comment by pongvarid** [comment]
พี่ต่ำเขียนไว้ให้แก่ในช่องราคารวม ครับ เเต่เดี่ยวผมจะ แก้ให้ครับ
