### ISSUE TITLE
(ปุน)_High หน้าแบ่งยอดขาย แสดงยอดที่ชำระ

### ISSUE THREAD

**Issue by satawat-t** [tarro55/kkc#20]
**ในหน้าแบ่งยอด User ทำการชำระเพิ่ม 7000 บาท แบ่งยอดจะต้องแบ่งได้แค่ 7000 บาท**
![image](https://user-images.githubusercontent.com/60998712/86244339-03d46980-bbd2-11ea-8aeb-f0df2eecf9dc.png)

![image](https://user-images.githubusercontent.com/60998712/86244378-15b60c80-bbd2-11ea-804a-05cd96bb274f.png)

![image](https://user-images.githubusercontent.com/60998712/86244609-704f6880-bbd2-11ea-90b5-627a973e094e.png)

**Comment by pbenzyk** [comment]
อันนี้ที่เช็คเกิดจากค่าข้อมูลเก่าไม่ครบ รบกวนลองเทสอีกรอบค่ะ

**Comment by satawat-t** [comment]
ลองเทสแล้วครับ ชำระคอร์สราคา 5000 บาท ครั้งแรกชำระ 3000 บาท แล้วทำการชำระเพิ่ม 2000 บาท
แต่ในหน้าแบ่งยอดขาย แสดงเป็น 2000 ทั้ง 2 รายการครับ
![image](https://user-images.githubusercontent.com/60998712/86537051-7f0d8680-bf16-11ea-9762-68dc361460dd.png)

![image](https://user-images.githubusercontent.com/60998712/86537026-61402180-bf16-11ea-99b2-385c0d703d9a.png)

**Comment by pbenzyk** [comment]
update issues
