### ISSUE TITLE
(ปุน)_Report_รายงานยอดขายสาขา(ยังเขียนไม่เสร็จ)

### ISSUE THREAD

**Issue by satawat-t** [tarro55/kkc#31]
![image](https://user-images.githubusercontent.com/60998712/86480826-fa393600-bd78-11ea-9288-685295e3b937.png)
ยอดชำระ - ยอดหักเข้าออฟฟิศ = ยอดสุทธิ
ตัวอย่าง ขายคอร์สราคา 7500 บาท
**ยอดเงินที่ชำระ** ยอดเงินที่เกิดจากการแบ่งยอดสาขา ในหน้าแบ่งยอด เช่น แบ่งยอดเข้าสาขา พารากอน 100% = 7500 บาท
**Advance** ขึ้นเป็น 0 เสมอ จะขึ้นมากกว่า 0 ก็ต่อเมื่ออัพคอร์ส (ตัวอย่าง2)
**ยอดหักเข้าออฟฟิศ** คิดจาก % ในการหักค่าธรรมเนียมในหน้าแบ่งยอด เช่น สาขาพารากอน แบ่งยอดไป 50% ลาดพร้าว 50%
ทำการหักเข้าออฟฟิศ 100% พารากอนจะแสดงเป็น 3750 บาท ลาดพร้าวจะแสดงเป็น 3750 บาท
ถ้าหักเข้าออฟฟิศ 90% (6750 บาท) พารากอนจะแสดงเป็น 3375 บาท ลาดพร้าว 3375 บาท
ถ้ามีแค่พารากอนสาขาเดียว ยอดหักเข้าออฟฟิศ 100% จะเป็น 7500 บาท
**ยอดสุทธิ** คือ ยอดแบ่งสาขา ที่เกิดในหน้าแบ่งยอด 100% = 7500 เข้าที่สาขา พารากอน แต่ต้องลบยอดหักเข้าออฟฟิศ

เงื่อนไข กรณีที่ ยอดชำระ - ยอดหักเข้าออฟฟิศ แล้วยอดสุทธิติดลบ ให้แสดงยอดสุทธิเป็น 0 และแสดงยอดหักเข้าออฟฟิศเท่าที่หักได้
เช่น แบ่งยอดสาขาพารากอน 50% (3750 บาท) แต่ทำการหักเข้าออฟฟิศ 100% (7500 บาท) ยอดสุทธิที่เกิดขึ้น จะเป็น 0 ทันที เพราะยอดที่เข้าสาขามีเพียง 3750 บาท และยอดหักเข้าออฟฟิศจะเท่า 3750 บาท(สูงสุดที่ยอดออฟฟิศจะหักได้ตามยอดของสาขาพารากอนที่ได้)
เช่น2 แบ่งยอดอีกครั้งแต่เป็นสาขา ลาดพร้าว อีก 50% (3750 บาท) แต่ User จะไม่ทำการหักเข้าออฟฟิศอีก เพราะด้านบนได้แบ่งยอด 100% เต็มไปหมดแล้ว ยอดชำระของลาดพร้าวจะเป็น 3750 บาท ยอดหักเข้าออฟฟิศจะเป็น 3750 บาท(คือยอดหักเข้าออฟฟิศที่เหลือ50% จากพารากอน)
**** ยอดหักเข้าออฟฟิศ เกิดจากการหักค่าธรรมเนียม ในหน้าแบ่งยอดขาย

ตัวอย่าง2 **กรณีอัพคอร์ส** จาก 7500 บาท ไป 12500 บาท (ลูกค้าชำระเพิ่ม 5000 บาท)
**ยอดเงินที่ชำระ** **รอถามออดิต** _จะคำณวนตามจำนวน % ที่แบ่งยอดสาขาในหน้าแบ่งยอด ของมูลค่าเต็มของคอร์สที่อัพ คือ 12500 บาท
ถ้าแบ่งยอดสาขาพารากอน 100% ยอดเงินที่ชำระจะเป็น 12500 บาท / แต่ถ้า 50% จะเป็น 6250 บาท
(ไม่ได้คำณวนจากมูลค่าที่แบ่งยอดได้ แต่คำณวนจาก % ที่แบ่งยอด) / ในหน้าแบ่งยอดเข้าสาขาพารากอน ถ้า100% มูลค่าจะเท่ากับ5000บาท คิดเป็น 100%_
**Advance** จะเท่ากับมูลค่าคอร์สเดิมที่ลูกค้านำมาอัพคอร์ส ในที่นี้คือ 7500 บาท
**ยอดสุทธิ

**Comment by satawat-t** [comment]
https://drive.google.com/file/d/1qHoZYUe2S69a87EamfTU7u2XqrlGDLED/view?usp=sharing

**Comment by pbenzyk** [comment]
รอออดิตเพิ่มเติม

**Comment by satawat-t** [comment]
การอัพคอร์ส จะสามารถเลือกคอร์สใหม่ได้เพียง 1 ตัวเท่านั้นครับ  ตามการใช้งานจริง หากลูกค้าต้องการคอร์สอีกตัวนึง / User จะทำการขายคอร์สแยกอีก 1 สัญญาครับ
