### ISSUE TITLE
(พืช+ปุน) การขายถาดแถม และการแบ่งยอดถาดแถม

### ISSUE THREAD

**Issue by satawat-t** [tarro55/kkc#32]
![image](https://user-images.githubusercontent.com/60998712/86490704-7d1aba80-bd92-11ea-8a66-e8aeb8858b66.png)
การขายถาดแถม ตอนนี้ระบบจะบันทึกค่าลง treatments.type_contract เป็น "credit"
ถ้าแก้ไขเป็น "giftset" สำหรับการแยกประเภทของถาดแถมจะโอเคไหมครับ จะได้ง่ายกับรายงานออดิต
สำหรับปุน ในหน้าแบ่งยอดขาย จะต้องไม่แสดงรายการของถาดแถมครับ เพราะไม่มีการชำระเงินเกิดขึ้นจริง
หรืออีกทางนึงถ้าไม่ให้แสดงรายการในหน้าแบ่งยอดคือไป where ที่ courses.is_web_credit_promotion != 1 
![image](https://user-images.githubusercontent.com/60998712/86490942-5e68f380-bd93-11ea-9d9c-6cb20d00321f.png)

**Comment by pbenzyk** [comment]
ตอนนี้ fix เป็น "_แสดงรายการในหน้าแบ่งยอดคือไป where ที่ courses.is_web_credit_promotion != 1_"
