### ISSUE TITLE
(ปุน)_Report_รายงานออดิต เพิ่ม Filter ประเภทสัญญา

### ISSUE THREAD

**Issue by satawat-t** [tarro55/kkc#33]
![image](https://user-images.githubusercontent.com/60998712/86491026-aab43380-bd93-11ea-8498-060836172fe7.png)
เพิ่ม Filter ประเภทสัญญาเป็น "สัญญาถาดแถม" ประเภทการชำระเป็น ทั่วไป
จำนวนครั้ง,ราคาต่อครั้ง,จำนวนทั้งสิ้น ยังไม่ถูกต้อง

รายละเอียดของข้อมูลถาดแถม ต้องแก้ที่ issue 32 ก่อนครับ
https://github.com/tarro55/kkc/issues/32

**Comment by satawat-t** [comment]
https://drive.google.com/file/d/1qHoZYUe2S69a87EamfTU7u2XqrlGDLED/view?usp=sharing

**Comment by pbenzyk** [comment]
update จำนวนครั้ง,ราคาต่อครั้ง,จำนวนทั้งสิ้น
