### ISSUE TITLE
(ปุน) การ cut down และ up course

### ISSUE THREAD

**Issue by satawat-t** [tarro55/kkc#41]
>ประวัติลูกค้า > รายละเอียดคอร์ส ในการ cutdown คอร์ส ข้ามเงื่อนไข pop-up ตรงนี้ และให้ User cut down ได้แบบใส่ตัวเลขอะไรก็ได้ ได้เอง
เพราะยังไงระบบก็ตำณวนไม่ถูกครับ
![image](https://user-images.githubusercontent.com/60998712/86613881-5ea7ff80-bfdc-11ea-8217-3cf63513b03a.png)

ในหน้าขายคอร์ส > อัพคอร์ส  ให้ User สามารถแก้ไขมูลค่าคอร์สเดิมที่จะนำมาอัพได้เอง
![image](https://user-images.githubusercontent.com/60998712/86613657-1be62780-bfdc-11ea-815c-d2fe8912cd46.png)

**Comment by pbenzyk** [comment]
Update Cutdown

**Comment by satawat-t** [comment]
ทดสอบ cut down คอร์ส Promotion Super Megadose 10 แถม Dip White 5 ครั้ง เมื่อใส่รหัสแล้วกดบันทึก ระบบแจ้งผิดพลาดครับ
CCHOF020070274
![image](https://user-images.githubusercontent.com/60998712/87006051-3a217280-c1ea-11ea-8655-a31b67d03f92.png)

**Comment by satawat-t** [comment]
> ทดสอบ cut down คอร์ส Promotion Super Megadose 10 แถม Dip White 5 ครั้ง เมื่อใส่รหัสแล้วกดบันทึก ระบบแจ้งผิดพลาดครับ
> CCHOF020070274
> ![image](https://user-images.githubusercontent.com/60998712/87006051-3a217280-c1ea-11ea-8655-a31b67d03f92.png)

ยังเจอ ข้อผิดพลาดอยู่ครับ

![image](https://user-images.githubusercontent.com/60998712/87501840-4abe6680-c68a-11ea-82a9-7c65728eddbc.png)

**Comment by pbenzyk** [comment]
ใช้ Username/password เดียวกันกับ Login ไหมคะ

**Comment by satawat-t** [comment]
> ใช้ Username/password เดียวกันกับ Login ไหมคะ

การคัตดาวน์ใช้ User : Pass เดียวกันกับ Login ครับ  ส่วนอัพคอร์สไม่ต้องใส่รหัสครับ

**Comment by satawat-t** [comment]
ยังเจอข้อผิดพลาดอยู่ครับ
รหัสลูกค้า : CIMQT01607000009
เลขที่สัญญา : CCHOF020071235
ลองทำการคัตดาวคอร์สแรกครับ
![image](https://user-images.githubusercontent.com/60998712/87866359-f88f8500-c9aa-11ea-96f7-27d9174932ec.png)
ใส่รหัส User : 63007  Pass : 63007 และกดบันทึก
![image](https://user-images.githubusercontent.com/60998712/87866344-c2ea9c00-c9aa-11ea-9549-287b0d62af2e.png)

**Comment by satawat-t** [comment]
วิดีโอที่เจอข้อผิดพลาดในการคัตดาวครับ
https://drive.google.com/file/d/1rbadz7lX_mVQz2WV1PF0SD-fmC_ii8Sx/view?usp=sharing

รายละเอียดในการคัตดาวหายไปครับ
![image](https://user-images.githubusercontent.com/60998712/87874803-066af780-c9f7-11ea-9308-1791d35faf80.png)

**Comment by satawat-t** [comment]
- ลองทำคัตดาวน์ คอร์ส Botox 
![image](https://user-images.githubusercontent.com/60998712/87878927-8c943780-ca11-11ea-8d17-cec5356780d4.png)
- หน้านี้ใส่จำนวนที่ต้องการคัตดาวน์ 40000 บาท เมื่อกดบันทึก หน้าเว็บนิ่งครับ ไม่มีอะไรขึ้น และไม่สามารถคัตดาวน์ได้ครับ
  (แสดงชื่อคอร์สผิดเป็น Filler ครับ)
![image](https://user-images.githubusercontent.com/60998712/87878894-5b1b6c00-ca11-11ea-9ebd-06c3e34b3bb9.png)

**Comment by satawat-t** [comment]
บันทึกได้แล้วครับ วงเงินคัตดาวน์ได้แล้วครับ แต่พอคัตดาวน์แล้วคอร์สไม่หายไปครับ
**รหัสลูกค้า :** CIMQT01607000009
**เลขที่สัญญา :** CCHOF020071250
![image](https://user-images.githubusercontent.com/60998712/87880609-30371500-ca1d-11ea-8424-360ad08e637b.png)
