### ISSUE TITLE
(ปุน)Transaction Error

### ISSUE THREAD

**Issue by satawat-t** [tarro55/kkc#5]
หน้าแบ่งยอดขายมีปัญหาตอนกดเข้าครับ
<img width="944" alt="Transaction_error" src="https://user-images.githubusercontent.com/60998712/86089637-cc32c800-bad2-11ea-8f29-2eea2c78f00e.png">

**Comment by pbenzyk** [comment]
Add the "treatment_id" column to the commission fees, commission branches, and commission sales tables.
