### ISSUE TITLE
(พืช) ตัดคอร์สมีตัวยา แต่ระบบไม่ตัดยาออกจากสต็อค

### ISSUE THREAD

**Issue by satawat-t** [tarro55/kkc#51]
![image](https://user-images.githubusercontent.com/60998712/87423317-4ea7a580-c604-11ea-861e-cddcf2b78b9f.png)

ตัดคอร์สแล้วใส่ยาตัวนี้จำนวน 1 หน่วย   ก่อนตัดคอร์สยามี 16 หน่วย หลังตัดคอร์สยาก็ยังมี 16 หน่วยเท่าเดิมครับ

![image](https://user-images.githubusercontent.com/60998712/87423503-a1815d00-c604-11ea-99af-fdef7081ab0f.png)

ยกเลิกตัดคอร์ส ตัวยาก็ไม่คืนค่ากลับไปสต็อคครับ

**Comment by pongvarid** [comment]
ตัด on hand และ treatmet amount

**Comment by satawat-t** [comment]
**table : stock_transactions** มันจะมี note "ใช้ในการตัดคอร์ส"
![image](https://user-images.githubusercontent.com/60998712/87561707-43797600-c6e7-11ea-9e31-b5f40fcc795f.png)
แต่ไม่ได้บันทึกข้อมูลลง **table : stock_transaction_lines** (จะมีผลกับ **รายงานยอดสต็อคคงเหลือรายวัน** https://github.com/tarro55/kkc/issues/63)
![image](https://user-images.githubusercontent.com/60998712/87562645-707a5880-c6e8-11ea-82dd-a2e0f02dbf70.png)

**Comment by satawat-t** [comment]
ยาตัวนี้มีในสต็อค 30 หน่วย
![image](https://user-images.githubusercontent.com/60998712/87851008-de0fca00-c91e-11ea-8bfb-058b4510b237.png)
ทำการตัดคอร์สโดยใส่ยาตัวนี้ 2 หน่วย
![image](https://user-images.githubusercontent.com/60998712/87850996-c6384600-c91e-11ea-8aa2-a8ff62a714d9.png)

เมื่อทำการตัดคอร์สเสร็จ จำนวนสต็อคไม่ลดลงครับ ยังคงเป็น 30 เท่าเดิม

**Comment by satawat-t** [comment]
1.ตัดคอร์สโดยใช้สูตรยา 20%s 5หน่วย
![image](https://user-images.githubusercontent.com/60998712/87866474-5e304100-c9ac-11ea-838d-b5bee8ac21e9.png)

2.ในหน้าประวัติการตัดคอร์ส แสดงตัวยาและจำนวนถูกต้อง
![image](https://user-images.githubusercontent.com/60998712/87866478-8750d180-c9ac-11ea-9a2d-3ef0e5a3b428.png)

3.Stock ยาตัวนี้ ก่อนตัดคอร์สมี 50หน่วย หลังตัดคอร์สเหลือ 45 หน่วย แสดงผลถูกต้อง
![image](https://user-images.githubusercontent.com/60998712/87866485-9768b100-c9ac-11ea-87a7-b73fe95e8b55.png)

4.ทำการยกเลิกตัดคอร์สที่ใช้ตัวยา 20%s
![image](https://user-images.githubusercontent.com/60998712/87866495-ac454480-c9ac-11ea-8fe6-2a68413330d8.png)

5.มาเช็คสต็อค จำนวนสต็อคไม่คืนค่ากลับมาเป็น 50 หน่วยครับ
![image](https://user-images.githubusercontent.com/60998712/87866506-ca12a980-c9ac-11ea-9846-d28ceb92b452.png)

**Comment by satawat-t** [comment]
อีกกรณีที่เจอก็คือ ถ้า User ใส่สูตรยา แล้วกดเพิ่มสูตรยาในคอร์สไปแล้ว สต็อคจะถูกตัดออกตั้งแต่ตอนเพิ่มสูตรยา(ยังไม่กดปุ่มดำเนินการตัดคอร์ส)
แล้ว User กดปุ่มยกเลิกรายการ ตัวยาจะถูกตัดออกสต็อคไป ทั้งๆที่ยังไม่ได้ตัดคอร์สครับ
![image](https://user-images.githubusercontent.com/60998712/87866611-17dbe180-c9ae-11ea-9376-f3c4214c4387.png)

**Comment by satawat-t** [comment]
เจอปัญหาตัดคอร์สแล้วตัวยาไม่ลดลง แล้วก็ยกเลิกการตัดคอร์สสต็อคไม่คืนค่า อีกแล้วครับ

แต่ถ้ากดลบสูตรยาในหน้าประวัติ แต่ไม่ได้ยกเลิกตัดคอร์ส ระบบจะคืนค่ากลับสต็อคครับ
![image](https://user-images.githubusercontent.com/60998712/87882057-a93b6a00-ca27-11ea-9315-07eaf2b7bdeb.png)

**Comment by satawat-t** [comment]
**- ตัดคอร์ส จำนวนยาในสต็อคลดลงแล้วครับ**
**- แต่พอยกเลิกตัดคอร์ส  ระบบไม่คืนจำนวนยาเข้าสต็อคให้ครับ**
