### ISSUE TITLE
(ปุน) รายงานแบ่งยอดแต่ละสาขา แสดงยอดหักเข้าออฟฟิศผิด

### ISSUE THREAD

**Issue by satawat-t** [tarro55/kkc#59]
![image](https://user-images.githubusercontent.com/60998712/87526967-ad792780-c6b5-11ea-933f-820dfff9ab16.png)
ในรายงาน แสดงรายการ Blink Laser 001 ยอดหักเข้าออฟฟิศ 8000 บาท 

แต่ในหน้าจัดการยอดขาย ยังไม่ได้มีการแบ่งยอดเลยครับ
![image](https://user-images.githubusercontent.com/60998712/87527117-ddc0c600-c6b5-11ea-9a6d-8cdfd01f0a95.png)

**Comment by pbenzyk** [comment]
เพิ่ม branch_id ที่ตาราง commission_fees

**Comment by satawat-t** [comment]
Login ด้วยสาขา บางนา
- ค้นหาข้อมูลแล้วไม่มีข้อมูลแสดงครับ
![image](https://user-images.githubusercontent.com/60998712/87866816-3d69ea80-c9b0-11ea-851e-196a374a337d.png)

ลอง Export excel ได้ และมีข้อมูล แต่ข้อมูลยอดหักเข้าออฟฟิศแสดงไม่ถูกต้องครับ
![image](https://user-images.githubusercontent.com/60998712/87866838-8d48b180-c9b0-11ea-93b0-ce6b8c9c2c4b.png)

เลขที่ใบเสร็จนี้ มีการหักค่าธรรมเนียม(ยอดหักเข้าออฟฟิศ)ไปแล้วครับ
![image](https://user-images.githubusercontent.com/60998712/87866853-acdfda00-c9b0-11ea-973d-b619a1f57b09.png)
