### ISSUE TITLE
(ปุน+พืช) รายงานที่ export แล้ว out of memory เพราะข้อมูลเยอะ

### ISSUE THREAD

**Issue by satawat-t** [tarro55/kkc#62]
- รายงานการซื้อซ้ำของลูกค้า
- รายงานเตือนคอร์สใกล้หมด

![image](https://user-images.githubusercontent.com/60998712/87555838-28efce80-c6e0-11ea-994f-5ae0fef7d2f9.png)

**Comment by pbenzyk** [comment]
fix เป็นเดือนปัจจุบันได้ไหมคะ

**Comment by satawat-t** [comment]
> fix เป็นเดือนปัจจุบันได้ไหมคะ

ได้ครับ แต่ปุนเช็คตอน export ด้วยนะครับ ว่า export ข้อมูลทั้งหมดได้ไหมนะครับ

**Comment by satawat-t** [comment]
- รายงานการซื้อซ้ำของลูกค้า Export แล้วขึ้นหน้าเว็บแบบนี้ครับ
![image](https://user-images.githubusercontent.com/60998712/87866714-3d1d1f80-c9af-11ea-8ba5-6b0eaf7ea09e.png)

![image](https://user-images.githubusercontent.com/60998712/87866737-65a51980-c9af-11ea-9265-3f026b45bb92.png)
