### ISSUE TITLE
(ปุน) หน้าจัดการยอดขาย กรณีมีการชำระเพิ่ม ระบบแสดงข้อมูลผิดครับ

### ISSUE THREAD

**Issue by satawat-t** [tarro55/kkc#68]
เลขที่ใบเสร็จ RE2007000885 มีการชำระเพิ่มมา 4000 บาท แต่ในหน้าแบ่งยอดแสดงผิดเป็น 12000 บาทครับ
![image](https://user-images.githubusercontent.com/60998712/87802151-f6c6a400-c87a-11ea-9917-f9a989ee1cb3.png)
ยอดใบเสร็จแรกจะเป็น 12000 บาท ครับ
![image](https://user-images.githubusercontent.com/60998712/87802250-165dcc80-c87b-11ea-83fb-3cde5ecd1ca8.png)

**Comment by pbenzyk** [comment]
อันไหนที่เป็นชำระเงินเพิ่ม รบกวนเปลี่ยนค่า payup = 1 ที่ ตาราง sale_payments
