### ISSUE TITLE
(ปุน) รายงานสรุปยอดที่ปรึกษาการขาย แสดงรายชื่อผิดครับ

### ISSUE THREAD

**Issue by satawat-t** [tarro55/kkc#70]
![image](https://user-images.githubusercontent.com/60998712/87848521-6edcaa80-c90b-11ea-8116-bc4dbcca5ed7.png)
รายชื่อในตารางจะแสดงผิดอยู่ครับ ชื่อของ 2 คนนี้ไม่ได้เป็นเซลล์ครับ แต่เป็นพนักงานที่ทำการขายครับ

รายงานที่แสดงรายละเอียดเมื่อกดชื่อเซลล์ก็ผิดครับ
![image](https://user-images.githubusercontent.com/60998712/87848688-c891a480-c90c-11ea-88c0-9dd149297d32.png)

**Comment by pbenzyk** [comment]
ขอรายละเอียดแต่ละฟิลด์ค่ะ

**Comment by satawat-t** [comment]
รายงานสรุปยอดที่ปรึกษาการขาย
- เงินที่ชำระ คือจำนวนเงินรวมทั้งหมด ที่ลูกค้าชำระมา ที่ได้ทำการแบ่งยอดให้กับเซลล์ ตามรูปภาพนี้คือจะได้ผลรวมคือ 1500+5000 = 6500 
![image](https://user-images.githubusercontent.com/60998712/87877742-3f609780-ca0a-11ea-9244-b1e8e696f3be.png)
- ยอดหัก คือจำนวนที่หักค่าธรรมเนียมในหน้าจัดการยอดขายรวมทั้งหมด ของรายการที่แบ่งให้เซลล์
![image](https://user-images.githubusercontent.com/60998712/87877777-69b25500-ca0a-11ea-8e62-5f1d935e8e0e.png)
- ยอดสุทธิ = เงินที่ชำระ - ยอดหัก

รายงานยอดที่ปรึกษาการขาย
- เงินที่ชำระ คือจำนวนเงินที่ลูกค้าชำระ แสดงเป็นรายทรีตเม้นท์ ในรายงานนี้จะแสดงออกเป็น 2 รายการ
   AHA Peel 001  1500 ,  Allergy Gone 001  5000
- ยอดหัก คือการหักค่าธรรมเนียมในหน้าจัดการยอกขาย แสดงเป็นรายทรีตเม้นท์ 
   AHA Peel 001   1500  ,  Allergy Gone 001   1000
- ยอดสุทธิ = เงินที่ชำระ - ยอดหัก
- ยอดเซลล์ = ยอดสุทธิ คำณวน%ใน commission_sales.commission_percent แสดงตามรายการของทรีตเม้นต์
ถ้าสมมุติว่า ยอดสุทธิคงเหลือ 10000 บาท แล้วในหน้าจัดการยอดขายแบ่งให้เซลล์ 50% เซลล์จะได้ 50% จาก ยอดสุทธิ คือ 5000 บาท
ถ้าแบ่งให้เซลล์ 100%  เซลล์จะได้ 10000 บาท เต็มจำนวนของยอดสุทธิ
- กลุ่ม/ประเภท จะมีอยู่ 2 แบบ  Treatment กับ Other  ฐานข้อมูลเราไม่สามารถแยกประเภทได้ครับ เพราะคอร์สแต่ละประเภทอยู่คนละที่
  ให้ปุนแสดง Default เป็น Other ครับ

**Comment by satawat-t** [comment]
- เลขที่ใบเสร็จนี้มีข้อมูลใน sale_payments.deleted_at แล้วครับ ไม่ต้องนำมาแสดงในรายงานนี้ และใน excel ครับ
![image](https://user-images.githubusercontent.com/60998712/87884274-9a5cb380-ca37-11ea-8633-aec932b6c3fd.png)

![image](https://user-images.githubusercontent.com/60998712/87884300-d859d780-ca37-11ea-8eee-de6f2ae3e4de.png)

และ
- ลองเปลี่ยนแปลงยอดหักค่าธรรมเนียม ในหน้าจัดการยอดขาย จาก 1500 บาท เป็น 300 บาท
  และเปลี่ยนยอดเซลล์เป็น 100%  3000 บาท
![image](https://user-images.githubusercontent.com/60998712/87884586-62567000-ca39-11ea-8130-f45b256a1d2d.png)

- ในรายงานแสดงยอดหักถูกต้อง  แต่การคำณวนยอดสุทธิผิดครับ เลยทำให้ยอดเซลล์ผิดตาม (ใน Excel ก็ผิดครับ)
![image](https://user-images.githubusercontent.com/60998712/87884609-a5184800-ca39-11ea-920d-4c27285b3994.png)
