### ISSUE TITLE
(ปุน) รายงานยอดขายประจำวัน

### ISSUE THREAD

**Issue by satawat-t** [tarro55/kkc#71]
- ช่องหักค่าธรรมเนียมไม่แสดงข้อมูลครับ (เป็นยอดเดียวกับหักเข้าออฟฟิศ ในรายงานสรุปยอดขายสาขา)
- ลอง Filter วันที่ 15 ถึง 15 รายการที่แสดงเป็นวันที่ 15 จริง  แต่คอลั่ม วันที่ชำระ แสดงเป็นวันที่ 19 ครับ
![image](https://user-images.githubusercontent.com/60998712/87868737-6b0c5f00-c9c3-11ea-9ee3-051a896ab1c0.png)

- Filter สาขา สำนักงานใหญ่ดูได้ทุกสาขา  และสาขาอื่นๆดูได้เฉพาะสาขาตัวเองครับ

- ในรูปแบบ Excel แสดงวันที่ถูกแล้วครับ แต่ช่องหักค่าธรรมเนียม ยังไม่มีครับ
![image](https://user-images.githubusercontent.com/60998712/87868769-ac047380-c9c3-11ea-94dd-4a3dc702aa21.png)

*ตัวอย่างรายงานสรุปยอดขายสาขา ที่มีการหักค่าธรรมเนียม
![image](https://user-images.githubusercontent.com/60998712/87868712-21237900-c9c3-11ea-8da1-d3ec19e6656a.png)

**Comment by pbenzyk** [comment]
Filter วันที่ จะอิงจาก commission_fees หรือ sale_payments คะ

**Comment by pbenzyk** [comment]
- [/ ] ช่องหักค่าธรรมเนียมไม่แสดงข้อมูลครับ
- [ /] ในรูปแบบ Excel แสดงวันที่ถูกแล้วครับ
- [/ ] Filter สาขา สำนักงานใหญ่ดูได้ทุกสาขา และสาขาอื่นๆดูได้เฉพาะสาขาตัวเองครับ
- [/ ] ในรูปแบบ Excel แสดงวันที่ถูกแล้วครับ แต่ช่องหักค่าธรรมเนียม ยังไม่มีครับ
- [ ] ลอง Filter วันที่ 15 ถึง 15 รายการที่แสดงเป็นวันที่ 15 จริง แต่คอลั่ม วันที่ชำระ แสดงเป็นวันที่ 19 ครับ

**Comment by satawat-t** [comment]
> Filter วันที่ จะอิงจาก commission_fees หรือ sale_payments คะ

วันที่อ้างอิงจาก sale_payments.created_at ครับ

**Comment by satawat-t** [comment]
- ลอง FIlter วันที่ด้วยวันที่ 15-15  ในหน้าเว็บแสดงผลถูกต้องแล้วครับ
![image](https://user-images.githubusercontent.com/60998712/87875220-fdc7f080-c9f9-11ea-9def-0dc1f68ff55f.png)


- แต่ใน Excel แสดงผลมากกว่าหน้าเว็บครับ และ Header แสดงเป็นทุกสาขาครับ
![image](https://user-images.githubusercontent.com/60998712/87875208-e6890300-c9f9-11ea-80e1-8f1fbc5b9d18.png)
