### ISSUE TITLE
(ปุน)รายงานค่าคอมมือ

### ISSUE THREAD

**Issue by satawat-t** [tarro55/kkc#8]
![image](https://user-images.githubusercontent.com/60998712/86147236-57d44500-bb23-11ea-83d5-f43190104ab0.png)

**Comment by pbenzyk** [comment]
Update รายงานค่าคอมมือ

**Comment by pbenzyk** [comment]
รอออดิตเพิ่มเติม

**Comment by satawat-t** [comment]
![image](https://user-images.githubusercontent.com/60998712/87291173-239c5380-c529-11ea-962c-9c324b6bcda6.png)
การแสดงค่าคอมมือที่เป็นการแสดงรายละเอียดรายบุคคล ปุนได้ทำไว้หรือยังครับ

**Comment by satawat-t** [comment]
รายละเอียดตามนี้นะครับ
https://drive.google.com/file/d/1iRzrsJIaka2Md1MmHK8IBOJu9dzMn-eh/view?usp=sharing

จะแสดงข้อมูลรายบุคคลตอนที่ User กดตรง row ของพนักงานที่จะต้องการจะดู แล้วถึงจะแสดงรายงานนี้ครับ
(คล้ายๆกับหน้า รายงานสินค้าเข้า-ออกในสต็อค)

> ![image](https://user-images.githubusercontent.com/60998712/87291173-239c5380-c529-11ea-962c-9c324b6bcda6.png)
> การแสดงค่าคอมมือที่เป็นการแสดงรายละเอียดรายบุคคล ปุนได้ทำไว้หรือยังครับ

**Comment by satawat-t** [comment]
รายงาน **ขายผลิตภัณฑ์** คือ รายงานที่แสดงค่าคอมของเซลล์ จากการแบ่งยอดให้เซลล์ ในหน้าแบ่งยอดขายครับ

**Comment by pbenzyk** [comment]
อัพเดต รายงานขายผลิตภัณฑ์
